### PR TITLE
Support older ghcs

### PR DESCRIPTION
**Pull request by gwils**
I would prefer to support older GHCs with this library since it's so simple and most of our dependencies allow us to do so.

Some things:
* I removed the dependency on papa since it does not support these older GHCs. I'd like if Papa worked with older GHCs too, but I haven't had time to do that yet.
* I removed a couple of doctest QuickCheck properties since they didn't work with the version of `template-haskell` that is installed with GHC 7.4. Do we think they're valuable to keep? If so I'm happy to add a separate QuickCheck suite to reinstate them (not as part of the doctests)

What do we reckon?

### CODE REVIEW

**Comment by dalaing** [comment]
You could potentially also update [this](https://github.com/qfpl/text1/blob/master/ci/ci.nix#L2) to get the same kind of testing happening on Hydra, although that may anger the non-determinism gods.

**Comment by tonymorris** [comment]
I think getting `papa` up to speed with earlier GHCs is a high priority. I agree with removing doctest and perhaps moving the tests to functions in other source files.

**Comment by gwils** [comment]
@dalaing I wouldn't want to anger them further. They've been pretty cross with me lately.

@tonymorris Good point. I will change the tests to completely remove doctest. I'll add a HUnit suite and a QuickCheck suite.

**Comment by gwils** [comment]
The tests are looking good now. I would like to merge this and make a new release to hackage. I'll take a look at Papa in a couple of weeks, and once Papa's working on those GHC versions, I'm happy to add it back in and make another hackage release.

Thoughts @tonymorris?

**Comment by tonymorris** [comment]
:+1:

**Pull request merged**
